# Server
server.port=${PORT:8080}
server.address=0.0.0.0
# Подключение к приватной базе Railway
spring.datasource.url=jdbc:postgresql://${PGHOST}:${PGPORT}/railway
spring.datasource.username=${PGUSER}
spring.datasource.password=${PGPASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

# Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
